<?php

/*  
    Copyright 2011, 2012 Mike Bell and Paul Danos

    This file is part of 20Swiss.
    
    20Swiss is free software: you can redistribute it and/or modify it under the
    terms of the GNU Affero General Public License as published by the Free
    Software Foundation, either version 3 of the License, or (at your option)
    any later version.

    20Swiss is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
    more details.

    You should have received a copy of the GNU Affero General Public License
    along with 20Swiss.  If not, see <http://www.gnu.org/licenses/>. 
*/

    include("header.php");

    $mid = $_GET['id'];
    try {
        $module = get_module($mid) ;
    } catch (Exception $e) {
        header_redirect("/");
    }
    
    $tourney = get_tournament($module['parent_id']);
    if (($tourney['tournament_privacy'] != TOURNAMENT_PUBLIC) && !(check_login() && tournament_isadmin($tourney['tournament_id'])))
        header_redirect("/");
    //if (!( (check_login() && tournament_isadmin($module['parent_id'])) ||

    $server_url="http://" . $_SERVER["SERVER_NAME"];
    header("Content-type: text/xml");
    echo '<?xml version="1.0" encoding="utf-8" ?>';
?>

<rss 
    xmlns:polo="http://seattleswiss.com/rss/poloModule/"
    xmlns:atom="http://www.w3.org/2005/Atom"
    version="2.0">

    <channel>
        <title><? echo $module['module_name']; ?></title>
        <link><? echo "$server_url/public/module/$mid/"; ?></link>
        <description>results automatically generated by Two Oh Swiss</description>
        <lastBuildDate><? echo date("D, d M Y H:i:s T", time()) ?></lastBuildDate>
        <language>en-us</language>
        <atom:link href="<? echo "$server_url/rss/$mid/";?>" rel="self" type="application/rss+xml" />

<?php  //ASSERT: ispublic($id)

function rss_disp_team($team, $s, $r) {
    echo "<polo:team>\n";
    $out = array( "uid" => $team['team_uid'], 
                  "name" => $team['team_name'], 
                  "result" => $r );
    if ($team['team_text']) { $out["comment"] = $team['team_text']; }
    if ($s > -1)            { $out["score"]   = $s; }
    foreach ($out as $key => $val) {
        echo "<polo:$key>$val</polo:$key>\n";
    }
    echo "</polo:team>\n";
}

function disp_item($scores, $teams, $game_id) {
    echo "<item>\n";
    if (count($scores) == 1) {
        echo "<title>{$teams[$scores[0]['team_id']]['team_name']} gets a bye</title>\n";
        rss_disp_team($teams[$scores[0]['team_id']], -1, 1);
    }
    // result should be derived in some more clever way
    elseif (count($scores) > 1) {
        $team_names = array_map(function ($t) use ($teams) { return $teams[$t['team_id']]['team_name']; }, $scores);
        echo "<title>".implode($team_names, " vs. ")."</title>\n";
        $max = max(array_map(function ($s) { return $s['score']; }, $scores));
        $scale = count(array_filter($scores, function ($s) use ($max) { return $s['score'] == $max; }));
        //count(array_filter($scores, function ($s) { return ($s['score'] == $max); }));
        foreach($scores as $s)
            rss_disp_team($teams[$s['team_id']], $s['score'], ($s['score'] == $max) ? (1/$scale) : 0);

        if ($scale > 1)
            $text = "Tie game: $max-$max";
        else {
            if ($scores[0]['score'] > $scores[1]['score'])
                $text = "{$team_names[0]} wins: {$scores[0]['score']}-{$scores[1]['score']}";
            else
                $text = "{$team_names[1]} wins: {$scores[1]['score']}-{$scores[0]['score']}";
        }
        echo "<description>$text</description>\n";

    }
    //<guid isPermaLink="false">1309792342</guid>
    //<pubDate>Thu, 03 May 2012 14:03:22 PDT</pubDate>
    //<description>team a wins against team b, 5-0</description>
    echo "<guid isPermaLink=\"false\">20Swiss:GameId=$game_id</guid>\n";
    echo "</item>\n";
}

    $db = connect_to_db();

    $teams= array();
    $tlist = sql_select_all("SELECT * FROM tblModuleTeams JOIN tblTeam USING (team_id) WHERE module_id = :mid", array(":mid" => $mid));
    if ($tlist) {
        foreach ($tlist as $t) {
            foreach ($t as $k => $v)
                $t[$k] = htmlentities($v);
            $teams[$t['team_id']] = $t;
        }
    }

    $rounds = sql_select_all("SELECT * FROM tblRound WHERE module_id = :mid ORDER BY round_number DESC", array(":mid" => $mid), $db);
    if ($rounds)
        foreach ($rounds as $r) {
            $games = sql_select_all("SELECT * FROM tblGame WHERE round_id = :rid ORDER BY game_id DESC", array(":rid" => $r['round_id']), $db);
            if ($games) 
                foreach ($games as $g) {
                    $scores = sql_select_all("SELECT * FROM tblGameTeams WHERE game_id = :gid", array(":gid" => $g['game_id']), $db);
                    if (count($scores) == count(array_filter( $scores, function ($t) { return ($t['score'] > -1); } )))
                        disp_item($scores, $teams, $g['game_id']);
                }
        }
?>
    </channel>
</rss>
